### ISSUE TITLE
Update module to use gitops terraform provider

### ISSUE THREAD

**Issue by balasgit** [cloud-native-toolkit/terraform-gitops-cp-datapower#18]
Update the cluster type

╷
│ Error: No value for required variable
│ 
│   on variables.tf line 32:
│   32: variable "cluster_type" {
│ 
│ The root module input variable "cluster_type" is not set, and has no
│ default value. Use a -var or -var-file command line argument to provide a
│ value for this variable.
╵
Error: Process completed with exit code 1.

**Comment by seansund** [comment]
You just need to provide a default value for cluster_type

**Comment by seansund** [comment]
Now it is failing because the namespace is not being passed in -

```
│ Error: Missing required argument
│ 
│   on module/main.tf line 93, in resource "gitops_module" "module":
│   93: resource gitops_module module {
│ 
│ The argument "namespace" is required, but no definition was found.
╵
```

https://github.com/cloud-native-toolkit/terraform-gitops-cp-datapower/blob/issue-496/main.tf#L98

**Comment by balasgit** [comment]
Fixed all the issues as module is looking for CP-datapower instances.

./.owner_module
./docs
./docs/gitops-structure-overview.png
ArgoCD config missing - argocd/2-services/cluster/default/instances/gitops-cp-datapower-ibm-datapower-instance.yaml
Validation failed

 More details about this error - https://github.com/cloud-native-toolkit/terraform-gitops-cp-datapower/actions/runs/3128956749/jobs/5096195733
